title: Sangeun Seo
logo: /assets/img/sangeun.png
description: >
  HCI Researcher | Education Technology Enthusiast
  <br><br>
  seseo98@dgist.ac.kr
show_downloads: false
# google_analytics:
theme: jekyll-theme-minimal
